export type EmployeeUser = {
  id?: number;
  name?: string;
  email?: string;
  department?: string;
  employeecode?: string;
  role?: string;
  designation?: string;
  reportingToId?: number | null;
  mustchangepassword?: boolean;
  dateOfBirth?: string | null;
  phone?: string | null;
  location?: string | null;
  bio?: string | null;
  profilePhotoUrl?: string | null;
  avatar_url?: string | null;
  age?: number | null;
  isFirstLogin?: boolean;
  onboardingCompleted?: boolean;
};
export type UserProfile = {
  id: number;
  employeecode?: string;
  name: string;
  email: string;
  department?: string | null;
  role?: string;
  designation?: string | null;
  reportingToId?: number | null;
  dateOfBirth?: string | null;
  phone?: string | null;
  location?: string | null;
  bio?: string | null;
  profilePhotoUrl?: string | null;
  age?: number | null;
  createdAt?: string;
  isFirstLogin?: boolean;
  onboardingCompleted?: boolean;
  emergencyContactName?: string | null;
  emergencyContactPhone?: string | null;
  bankAccountName?: string | null;
  bankAccountNumber?: string | null;
  bankIfsc?: string | null;
};
