import type { OrgTreeRoot } from './types';

export const DEFAULT_ORG_DATA: OrgTreeRoot = {
  id: '1',
  name: 'Ashish Mishra',
  title: 'CEO & Founder',
  level: 'root',
  photo: null,
  status: 'online',
  skills: [],
  tags: [],
  children: [
    {
      id: '2',
      type: 'coparent',
      parents: [
        {
          id: '2a',
          name: 'XYZ',
          title: 'COO',
          level: 'c-suite',
          photo: null,
          status: 'online',
          skills: [],
          tags: [],
        },
        {
          id: '2b',
          name: 'ABC',
          title: 'Director',
          level: 'director',
          photo: null,
          status: 'online',
          skills: [],
          tags: [],
        },
      ],
      children: [
        {
          id: '3',
          name: 'Geetika',
          title: 'Manager',
          level: 'manager',
          photo: null,
          status: 'online',
          skills: [],
          tags: [],
          children: [
            {
              id: '5',
              name: 'Abhivardhan',
              title: 'Team Lead',
              level: 'lead',
              photo: null,
              status: 'online',
              skills: [],
              tags: [],
              children: [
                {
                  id: '9',
                  name: 'Pari',
                  title: 'Intern',
                  level: 'intern',
                  photo: null,
                  status: 'online',
                  skills: [],
                  tags: [],
                  children: [],
                },
              ],
            },
            {
              id: '6',
              name: 'Sahil',
              title: 'Team Lead',
              level: 'lead',
              photo: null,
              status: 'online',
              skills: [],
              tags: [],
              children: [],
            },
            {
              id: '10',
              name: 'Ananya',
              title: 'Team Lead',
              level: 'lead',
              photo: null,
              status: 'online',
              skills: ['Design', 'UX'],
              tags: ['Creative'],
              children: [],
            },
            {
              id: '11',
              name: 'Rohan',
              title: 'Intern',
              level: 'intern',
              photo: null,
              status: 'online',
              skills: ['Research'],
              tags: ['Operations'],
              children: [],
            },
          ],
        },
        {
          id: '4',
          name: 'Hemant Singh',
          title: 'Manager',
          level: 'manager',
          photo: null,
          status: 'online',
          skills: [],
          tags: [],
          children: [
            {
              id: '7',
              name: 'Vikram',
              title: 'Team Lead',
              level: 'lead',
              photo: null,
              status: 'online',
              skills: [],
              tags: [],
              children: [],
            },
            {
              id: '8',
              name: 'Rakshit',
              title: 'Team Lead',
              level: 'lead',
              photo: null,
              status: 'online',
              skills: [],
              tags: [],
              children: [],
            },
            {
              id: '12',
              name: 'Priya',
              title: 'Team Lead',
              level: 'lead',
              photo: null,
              status: 'online',
              skills: ['Analytics'],
              tags: ['Data'],
              children: [],
            },
            {
              id: '13',
              name: 'Kabir',
              title: 'Intern',
              level: 'intern',
              photo: null,
              status: 'away',
              skills: ['QA'],
              tags: ['Quality'],
              children: [],
            },
          ],
        },
      ],
    },
  ],
};

export const STORAGE_KEY = 'orgChart';
